tap 'caskroom/cask'
tap 'homebrew/boneyard'
tap 'homebrew/brewdler'
tap 'homebrew/bundle'
brew 'libyaml'
brew 'openssl'
brew 'ansible'
brew 'gdbm'
brew 'heroku-toolbelt'
brew 'lua'
brew 'node'
brew 'xz'
brew 'readline'
brew 'sqlite'
brew 'python3'
brew 'vim', args: ['override-system-vi', 'with-lua', 'with-python3']
brew 'wget'
cask '==> We need to make Caskroom for the first time at /opt/homebrew-cask/Caskroom'
cask '==> We'll set permissions properly so we won't need sudo in the future'
